FROM node:lts-alpine

LABEL maintainer="Fred Gauthier <fred.gauthier.dev@gmail.com>" \
    Description="A lightweigth Nodejs container for Symfony with Xdebug and Composer, build with Alpine"


WORKDIR /home/docker

#RUN apk update \
#    && npm install  nodemon -g \
#    && rm -rf /var/cache/apk/*

#CMD ["npm", "run", "watch"]

